version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./frontend:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # This is needed for the frontend to connect to the host's X server.
